package com.xinbo.fundstransfer.domain.entity;
// Generated 2017-6-27 10:11:57 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

/**
 * AccountStatistics generated by hbm2java
 */
@Entity
@Table(name = "biz_account")
@JsonInclude(Include.NON_NULL)
public class AccountStatistics implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int type;
	private int id;
	private String account;
	private BigDecimal bankamount;
	private BigDecimal bankfee;
	private int bankcount;
	private BigDecimal tradingamount;
	private BigDecimal tradingfee;
	private int tradingcount;
	private int counts;
	private String alias;
	private String owner;
	private String banktype;
	private String handicapname;
	private String bankname;

	@Transient
	public int getBankcount() {
		return bankcount;
	}

	public void setBankcount(int bankcount) {
		this.bankcount = bankcount;
	}

	@Transient
	public int getTradingcount() {
		return tradingcount;
	}

	public void setTradingcount(int tradingcount) {
		this.tradingcount = tradingcount;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "account")
	public String getAccount() {
		return account;
	}

	public void setAccount(String account) {
		this.account = account;
	}

	@Transient
	public BigDecimal getBankamount() {
		return bankamount;
	}

	public void setBankamount(BigDecimal bankamount) {
		this.bankamount = bankamount;
	}

	@Transient
	public BigDecimal getBankfee() {
		return bankfee;
	}

	public void setBankfee(BigDecimal bankfee) {
		this.bankfee = bankfee;
	}

	@Transient
	public BigDecimal getTradingamount() {
		return tradingamount;
	}

	public void setTradingamount(BigDecimal tradingamount) {
		this.tradingamount = tradingamount;
	}

	@Transient
	public BigDecimal getTradingfee() {
		return tradingfee;
	}

	public void setTradingfee(BigDecimal tradingfee) {
		this.tradingfee = tradingfee;
	}

	public AccountStatistics() {
		super();
	}

	@Column(name = "type")
	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Transient
	public int getCounts() {
		return counts;
	}

	public void setCounts(int counts) {
		this.counts = counts;
	}

	/**
	 * @return the alias
	 */
	public String getAlias() {
		return alias;
	}

	/**
	 * @param alias the alias to set
	 */
	public void setAlias(String alias) {
		this.alias = alias;
	}

	/**
	 * @return the owner
	 */
	public String getOwner() {
		return owner;
	}

	/**
	 * @param owner the owner to set
	 */
	public void setOwner(String owner) {
		this.owner = owner;
	}

	/**
	 * @return the banktype
	 */
	public String getBanktype() {
		return banktype;
	}

	/**
	 * @param banktype the banktype to set
	 */
	public void setBanktype(String banktype) {
		this.banktype = banktype;
	}

	/**
	 * @return the handicapname
	 */
	public String getHandicapname() {
		return handicapname;
	}

	/**
	 * @param handicapname the handicapname to set
	 */
	public void setHandicapname(String handicapname) {
		this.handicapname = handicapname;
	}

	/**
	 * @return the bankname
	 */
	public String getBankname() {
		return bankname;
	}

	/**
	 * @param bankname the bankname to set
	 */
	public void setBankname(String bankname) {
		this.bankname = bankname;
	}

	public AccountStatistics(int type, int id, String account, BigDecimal bankamount, BigDecimal bankfee, int bankcount,
			BigDecimal tradingamount, BigDecimal tradingfee, int tradingcount, int counts, String alias, String owner,
			String banktype, String handicapname, String bankname) {
		super();
		this.type = type;
		this.id = id;
		this.account = account;
		this.bankamount = bankamount;
		this.bankfee = bankfee;
		this.bankcount = bankcount;
		this.tradingamount = tradingamount;
		this.tradingfee = tradingfee;
		this.tradingcount = tradingcount;
		this.counts = counts;
		this.alias = alias;
		this.owner = owner;
		this.banktype = banktype;
		this.handicapname = handicapname;
		this.bankname = bankname;
	}

	

}
