package com.xinbo.fundstransfer.domain.entity;
// Generated 2017-6-27 10:11:57 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BizHandicap generated by hbm2java
 */
@Entity
@Table(name = "biz_handicap")
public class BizHandicap implements java.io.Serializable {

	private Integer id;
	private String uri;
	private String name;
	private String code;
	private Integer status;
	private String apiKey;
	private Integer zone;

	public BizHandicap() {
	}

	public BizHandicap(String uri, String name, String code) {
		this.uri = uri;
		this.name = name;
		this.code = code;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "uri", length = 60)
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "api_key", length = 45)
	public String getApiKey() {
		return apiKey;
	}

	public void setApiKey(String apiKey) {
		this.apiKey = apiKey;
	}

	@Column(name = "zone")
	public Integer getZone() {
		return zone;
	}

	public void setZone(Integer zone) {
		this.zone = zone;
	}

	@Override
	public String toString() {
		return "BizHandicap{" + "id=" + id + ", uri='" + uri + '\'' + ", name='" + name + '\'' + ", code='" + code
				+ '\'' + ", status=" + status + ", apiKey='" + apiKey + '\'' + ", zone=" + zone + '}';
	}
}
