package com.xinbo.fundstransfer.domain.entity;
// Generated 2017-6-27 10:11:57 by Hibernate Tools 5.2.3.Final

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.xinbo.fundstransfer.domain.enums.IncomeRequestStatus;
import com.xinbo.fundstransfer.domain.enums.IncomeRequestType;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.Objects;

/**
 * BizIncomeRequest generated by hbm2java
 */
@Entity
@Table(name = "biz_income_request")
@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class BizIncomeRequest {

	private Long id;
	private Integer level;
	private Integer handicap;
	private Integer status;
	private BigDecimal amount;
	private Date createTime;
	private Date updateTime;
	private String remark;
	private Integer type;
	private String orderNo;
	private Integer operator;
	private Integer fromId;
	private String fromAccount;
	private Integer toId;
	private String toAccount;
	private String memberCode;
	private String memberUserName;
	private String memberRealName;
	private BigDecimal fee;
	private String toAccountBank;

	private String levelName;
	private String handicapName;
	private String typeName;
	private String statusName;
	private String operatorUid;
	private String fromOwner;
	private String fromAlias;
	private String fromBankType;
	private String toOwner;
	private String toAlias;
	private String toBankType;
	private Long timeconsume;
	private String createStr;

	private BigDecimal thirdBalance;
	private BigDecimal thirdBankBalance;
	
	private String chatPayBzm;
	private String chatPayRoomNum;
	private String chatPayRoomToken;
	private String chatPayBizId;

	public BizIncomeRequest() {
	}

	// 构造出款任务中三方出款或者拆单出款 保存到下发记录
	public BizIncomeRequest(BizOutwardRequest req, Integer thirdId, BigDecimal thirdOutAmount, BigDecimal feeVal,
			Integer operator, BizAccount thirdAccount, Long timeconsume) {

		this.amount = thirdOutAmount;
		this.createTime = new Date();
		this.orderNo = req.getOrderNo();
		this.type = IncomeRequestType.THIRDOUTFORMEMBER.getType();
		this.status = IncomeRequestStatus.Matched.getStatus();
		this.handicap = req.getHandicap();
		this.level = req.getLevel();
		this.fee = feeVal;
		this.memberRealName = req.getMember();
		this.memberUserName = req.getMember();
		this.fromId = thirdId;
		this.remark = IncomeRequestType.THIRDOUTFORMEMBER.getMsg() + ",金额:" + thirdOutAmount + ",总金额:"
				+ req.getAmount();
		this.operator = operator;
		this.fromAccount = Objects.nonNull(thirdAccount) ? thirdAccount.getAccount() : null;
		this.thirdBalance = Objects.nonNull(thirdAccount) ? thirdAccount.getBalance() : null;
		// 拆单完成的 这个值目前没有传入
		this.thirdBankBalance = BigDecimal.ZERO;
		this.toAccount = req.getToAccount();
		this.toAccountBank = req.getToAccountBank();
		this.timeconsume = timeconsume;
	}

	public BizIncomeRequest(Integer level, Integer handicap, Integer status, BigDecimal amount, Date createTime,
			Date updateTime, String remark, Integer type, String orderNo, Integer fromId, Integer toId,
			String fromAccount, String toAccount) {
		this.level = level;
		this.handicap = handicap;
		this.status = status;
		this.amount = amount;
		this.createTime = createTime;
		this.updateTime = updateTime;
		this.remark = remark;
		this.type = type;
		this.orderNo = orderNo;
		this.fromId = fromId;
		this.toId = toId;
		this.fromAccount = fromAccount;
		this.toAccount = toAccount;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return this.level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "handicap")
	public Integer getHandicap() {
		return this.handicap;
	}

	public void setHandicap(Integer handicap) {
		this.handicap = handicap;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19)
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "order_no", length = 45)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "operator")
	public Integer getOperator() {
		return operator;
	}

	public void setOperator(Integer operator) {
		this.operator = operator;
	}

	@Column(name = "from_account", length = 32)
	public String getFromAccount() {
		return fromAccount;
	}

	public void setFromAccount(String fromAccount) {
		this.fromAccount = fromAccount;
	}

	@Column(name = "from_id")
	public Integer getFromId() {
		return fromId;
	}

	public void setFromId(Integer fromId) {
		this.fromId = fromId;
	}

	@Column(name = "to_id")
	public Integer getToId() {
		return toId;
	}

	public void setToId(Integer toId) {
		this.toId = toId;
	}

	@Column(name = "to_account")
	public String getToAccount() {
		return toAccount;
	}

	public void setToAccount(String toAccount) {
		this.toAccount = toAccount;
	}

	@Column(name = "member_user_name", length = 32)
	public String getMemberUserName() {
		return memberUserName;
	}

	public void setMemberUserName(String memberUserName) {
		this.memberUserName = memberUserName;
	}

	@Column(name = "member_real_name", length = 32)
	public String getMemberRealName() {
		return memberRealName;
	}

	public void setMemberRealName(String memberRealName) {
		this.memberRealName = memberRealName;
	}

	@Transient
	public String getLevelName() {
		return levelName;
	}

	public void setLevelName(String levelName) {
		this.levelName = levelName;
	}

	@Transient
	public String getHandicapName() {
		return handicapName;
	}

	public void setHandicapName(String handicapName) {
		this.handicapName = handicapName;
	}

	@Transient
	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Transient
	public String getStatusName() {
		return statusName;
	}

	public void setStatusName(String statusName) {
		this.statusName = statusName;
	}

	@Column(name = "member_code")
	public String getMemberCode() {
		return memberCode;
	}

	public void setMemberCode(String memberCode) {
		this.memberCode = memberCode;
	}

	@Transient
	public String getOperatorUid() {
		return operatorUid;
	}

	public void setOperatorUid(String operatorUid) {
		this.operatorUid = operatorUid;
	}

	@Column(name = "fee")
	public BigDecimal getFee() {
		return fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	@Column(name = "to_account_bank")
	public String getToAccountBank() {
		return toAccountBank;
	}

	public void setToAccountBank(String toAccountBank) {
		this.toAccountBank = toAccountBank;
	}

	@Column(name = "time_consuming")
	public Long getTimeconsume() {
		return timeconsume;
	}

	public void setTimeconsume(Long timeconsume) {
		this.timeconsume = timeconsume;
	}

	@Column(name = "third_balance")
	public BigDecimal getThirdBalance() {
		return thirdBalance;
	}

	public void setThirdBalance(BigDecimal thirdBalance) {
		this.thirdBalance = thirdBalance;
	}

	@Column(name = "third_bank_balance")
	public BigDecimal getThirdBankBalance() {
		return thirdBankBalance;
	}

	public void setThirdBankBalance(BigDecimal thirdBankBalance) {
		this.thirdBankBalance = thirdBankBalance;
	}
	
	@Column(name = "chat_pay_bzm")
	public String getChatPayBzm() {
		return chatPayBzm;
	}
	
	public void setChatPayBzm(String chatPayBzm) {
		this.chatPayBzm = chatPayBzm;
	}
	
	@Column(name = "chat_pay_room_num")
	public String getChatPayRoomNum() {
		return chatPayRoomNum;
	}
	
	public void setChatPayRoomNum(String chatPayRoomNum) {
		this.chatPayRoomNum = chatPayRoomNum;
	}
	
	@Column(name = "chat_pay_room_token")
	public String getChatPayRoomToken() {
		return chatPayRoomToken;
	}
	
	public void setChatPayRoomToken(String chatPayRoomToken) {
		this.chatPayRoomToken = chatPayRoomToken;
	}
	
	@Column(name = "chat_pay_biz_id")
	public String getChatPayBizId() {
		return chatPayBizId;
	}
	
	public void setChatPayBizId(String chatPayBizId) {
		this.chatPayBizId = chatPayBizId;
	}

	@Transient
	public String getFromOwner() {
		return fromOwner;
	}

	public void setFromOwner(String fromOwner) {
		this.fromOwner = fromOwner;
	}

	@Transient
	public String getFromAlias() {
		return fromAlias;
	}

	public void setFromAlias(String fromAlias) {
		this.fromAlias = fromAlias;
	}

	@Transient
	public String getFromBankType() {
		return fromBankType;
	}

	public void setFromBankType(String fromBankType) {
		this.fromBankType = fromBankType;
	}

	@Transient
	public String getToOwner() {
		return toOwner;
	}

	public void setToOwner(String toOwner) {
		this.toOwner = toOwner;
	}

	@Transient
	public String getToAlias() {
		return toAlias;
	}

	public void setToAlias(String toAlias) {
		this.toAlias = toAlias;
	}

	@Transient
	public String getToBankType() {
		return toBankType;
	}

	public void setToBankType(String toBankType) {
		this.toBankType = toBankType;
	}

	@Transient
	public String getCreateStr() {
		return createStr;
	}

	public void setCreateStr(String createStr) {
		this.createStr = createStr;
	}

	@Override
	public String toString() {
		return "BizIncomeRequest{" + "id=" + id + ", level=" + level + ", handicap=" + handicap + ", status=" + status
				+ ", amount=" + amount + ", createTime=" + createTime + ", updateTime=" + updateTime + ", remark='"
				+ remark + '\'' + ", type=" + type + ", orderNo='" + orderNo + '\'' + ", operator=" + operator
				+ ", fromId=" + fromId + ", fromAccount='" + fromAccount + '\'' + ", toId=" + toId + ", toAccount='"
				+ toAccount + '\'' + ", memberCode=" + memberCode + ", memberUserName='" + memberUserName + '\''
				+ ", memberRealName='" + memberRealName + '\'' + ", fee=" + fee + ", toAccountBank='" + toAccountBank
				+ '\'' + ", levelName='" + levelName + '\'' + ", handicapName='" + handicapName + '\'' + ", typeName='"
				+ typeName + '\'' + ", statusName='" + statusName + '\'' + ", operatorUid='" + operatorUid + '\''
				+ ", fromOwner='" + fromOwner + '\'' + ", fromAlias='" + fromAlias + '\'' + ", fromBankType='"
				+ fromBankType + '\'' + ", toOwner='" + toOwner + '\'' + ", toAlias='" + toAlias + '\''
				+ ", toBankType='" + toBankType + '\'' + ", timeconsume=" + timeconsume + ", createStr='" + createStr
				+ '\'' + ", thirdBalance=" + thirdBalance + ", thirdBankBalance=" + thirdBankBalance + '}';
	}

	@Transient
	public Integer findOid() {
		if (orderNo == null) {
			throw new IllegalArgumentException("orderNo为空");
		}
		String[] parts = orderNo.split("O");
		if (parts.length != 2) {
			throw new IllegalArgumentException("orderNo格式错误");
		}

		return Integer.parseInt(parts[1]);
	}

	@Transient
	public byte findChannelType() {
		if (this.type == null) {
			throw new IllegalArgumentException("type为空");
		}
		if (this.type.equals(IncomeRequestType.PlatFromAli.getType())) {
			return (byte) 1;
		} else if (this.type.equals(IncomeRequestType.PlatFromWechat.getType())) {
			return (byte) 2;
		} else {
			throw new IllegalArgumentException("type不是支付宝或微信入款");
		}
	}




	/**
	 * 出款类型(出款通道类型)
	 */
	@Transient
	public IncomeRequestType getIncomeRequestType() {
		return 	IncomeRequestType.getByNumber(this.type);
	}
}
