package com.xinbo.fundstransfer.domain.entity;
// Generated 2017-6-27 10:11:57 by Hibernate Tools 5.2.3.Final

import javax.persistence.*;

/**
 * BizLevel generated by hbm2java
 */
@Entity
@Table(name = "biz_level")
public class BizLevel implements java.io.Serializable {

	private Integer id;
	private String name;
	private String code;
	private Integer handicapId;
	/** 状态：0-停用，1-启用,2-删除 */
	private int status;
	/** 内外层： 1 外层 2 内层 */
	private Integer currSysLevel;

	private String handicapName;
	private String currSysLevelName;

	public BizLevel() {
	}

	public BizLevel(int handicapId) {
		this.handicapId = handicapId;
	}

	public BizLevel(String name, String code, int handicapId, int status) {
		this.name = name;
		this.code = code;
		this.handicapId = handicapId;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "handicap_id", nullable = false)
	public Integer getHandicapId() {
		return this.handicapId;
	}

	public void setHandicapId(Integer handicapId) {
		this.handicapId = handicapId;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "curr_sys_level")
	public Integer getCurrSysLevel() {
		return currSysLevel;
	}

	public void setCurrSysLevel(Integer currSysLevel) {
		this.currSysLevel = currSysLevel;
	}

	@Transient
	public String getHandicapName() {
		return handicapName;
	}

	public void setHandicapName(String handicapName) {
		this.handicapName = handicapName;
	}

	@Transient
	public String getCurrSysLevelName() {
		return currSysLevelName;
	}

	public void setCurrSysLevelName(String currSysLevelName) {
		this.currSysLevelName = currSysLevelName;
	}
}
