package com.xinbo.fundstransfer.domain.entity;
// Generated 2017-6-27 10:11:57 by Hibernate Tools 5.2.3.Final

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.xinbo.fundstransfer.domain.enums.OutwardRequestType;

import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * BizOutwardRequest generated by hbm2java
 */
@Entity
@Table(name = "biz_outward_request")
@JsonInclude(Include.NON_NULL)
public class BizOutwardRequest implements java.io.Serializable {

	private Long id;
	private String orderNo;
	private Integer handicap;
	private String member;
	private String memberCode;
	private BigDecimal amount;
	private Date createTime;
	private Date updateTime;
	private int status;
	private String remark;
	private String review;
	private Integer reviewer;
	private Integer timeConsuming;
	private String toAccountName;
	private String toAccount;
	private String toAccountOwner;
	private String toAccountBank;
	private Integer level;

	// mark 2019-04-16 新增 outIp
	private String outIp;

	// mark 2019-05-23 新增 bankProvince 和 bankCity
	private String bankProvince;
	private String bankCity;

	private String reviewerUid;

	private String chatPayBzm;
	private String chatPayQrContent;
	private String chatPayRoomNum;
	private String chatPayRoomToken;
	private String chatPayBizId;	
	private Integer type; //出款类型，见 OutwardRequestType
	public BizOutwardRequest() {
	}

	public BizOutwardRequest(String orderNo, Integer handicap, String member, BigDecimal amount, Date createTime,
			Integer status, String remark, Integer reviewer, Integer timeConsuming) {
		this.orderNo = orderNo;
		this.handicap = handicap;
		this.member = member;
		this.amount = amount;
		this.createTime = createTime;
		this.status = status;
		this.remark = remark;
		this.reviewer = reviewer;
		this.timeConsuming = timeConsuming;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "order_no", length = 45)
	public String getOrderNo() {
		return this.orderNo;
	}

	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	@Column(name = "handicap", length = 45)
	public Integer getHandicap() {
		return this.handicap;
	}

	public void setHandicap(Integer handicap) {
		this.handicap = handicap;
	}

	@Column(name = "member", length = 45)
	public String getMember() {
		return this.member;
	}

	public void setMember(String member) {
		this.member = member;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Column(name = "type")
	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "remark", length = 100)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "reviewer")
	public Integer getReviewer() {
		return this.reviewer;
	}

	public void setReviewer(Integer reviewer) {
		this.reviewer = reviewer;
	}

	@Column(name = "time_consuming")
	public Integer getTimeConsuming() {
		return this.timeConsuming;
	}

	public void setTimeConsuming(Integer timeConsuming) {
		this.timeConsuming = timeConsuming;
	}

	@Column(name = "to_account_name")
	public String getToAccountName() {
		return toAccountName;
	}

	public void setToAccountName(String toAccountName) {
		this.toAccountName = toAccountName;
	}

	@Column(name = "to_account")
	public String getToAccount() {
		return toAccount;
	}

	public void setToAccount(String toAccount) {
		this.toAccount = toAccount;
	}

	@Column(name = "to_account_owner")
	public String getToAccountOwner() {
		return toAccountOwner;
	}

	public void setToAccountOwner(String toAccountOwner) {
		this.toAccountOwner = toAccountOwner;
	}

	@Column(name = "level")
	public Integer getLevel() {
		return level;
	}

	public void setLevel(Integer level) {
		this.level = level;
	}

	@Column(name = "member_code")
	public String getMemberCode() {
		return memberCode;
	}

	public void setMemberCode(String memberCode) {
		this.memberCode = memberCode;
	}

	@Column(name = "update_time")
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "to_account_bank")
	public String getToAccountBank() {
		return toAccountBank;
	}

	public void setToAccountBank(String toAccountBank) {
		this.toAccountBank = toAccountBank;
	}

	@Column(name = "review")
	public String getReview() {
		return review;
	}

	public void setReview(String review) {
		this.review = review;
	}

	@Transient
	public String getReviewerUid() {
		return reviewerUid;
	}

	public void setReviewerUid(String reviewerUid) {
		this.reviewerUid = reviewerUid;
	}

	/**
	 * @return the outIp
	 */
	@Column(name = "out_ip", length = 100)
	public String getOutIp() {
		return outIp;
	}

	/**
	 * @param outIp
	 *            the outIp to set
	 */
	public void setOutIp(String outIp) {
		this.outIp = outIp;
	}

	/**
	 * @return the outIp
	 */
	@Column(name = "bank_province", length = 36)
	public String getBankProvince() {
		return bankProvince;
	}

	public void setBankProvince(String bankProvince) {
		this.bankProvince = bankProvince;
	}

	/**
	 * @return the outIp
	 */
	@Column(name = "bank_city", length = 36)
	public String getBankCity() {
		return bankCity;
	}

	public void setBankCity(String bankCity) {
		this.bankCity = bankCity;
	}

	@Column(name = "chat_pay_bzm")
	public String getChatPayBzm() {
		return chatPayBzm;
	}
	
	public void setChatPayBzm(String chatPayBzm) {
		this.chatPayBzm = chatPayBzm;
	}
	
	@Column(name = "chat_pay_qr_content")
	public String getChatPayQrContent() {
		return chatPayQrContent;
	}
	
	public void setChatPayQrContent(String chatPayQrContent) {
		this.chatPayQrContent = chatPayQrContent;
	}
	
	@Column(name = "chat_pay_room_num")
	public String getChatPayRoomNum() {
		return chatPayRoomNum;
	}
	
	public void setChatPayRoomNum(String chatPayRoomNum) {
		this.chatPayRoomNum = chatPayRoomNum;
	}
	
	@Column(name = "chat_pay_room_token")
	public String getChatPayRoomToken() {
		return chatPayRoomToken;
	}
	
	public void setChatPayRoomToken(String chatPayRoomToken) {
		this.chatPayRoomToken = chatPayRoomToken;
	}
	
	@Column(name = "chat_pay_biz_id")
	public String getChatPayBizId() {
		return chatPayBizId;
	}
	
	public void setChatPayBizId(String chatPayBizId) {
		this.chatPayBizId = chatPayBizId;
	}	




	@Override
	public String toString() {
		return "BizOutwardRequest{" + "id=" + id + ", orderNo='" + orderNo + '\'' + ", handicap=" + handicap
				+ ", member='" + member + '\'' + ", memberCode=" + memberCode + ", amount=" + amount + ", createTime="
				+ createTime + ", updateTime=" + updateTime + ", status=" + status + ", remark='" + remark + '\''
				+ ", review='" + review + '\'' + ", reviewer=" + reviewer + ", timeConsuming=" + timeConsuming
				+ ", toAccountName='" + toAccountName + '\'' + ", toAccount='" + toAccount + '\'' + ", toAccountOwner='"
				+ toAccountOwner + '\'' + ", toAccountBank='" + toAccountBank + '\'' + ", level=" + level + ", outIp='"
				+ outIp + '\'' + ", bankProvince='" + bankProvince + '\'' + ", bankCity='" + bankCity + '\''
				+ ", reviewerUid='" + reviewerUid + '\'' + '}';
	}
	
	@Transient
	public Integer findOid() {
		if(orderNo == null) {
			throw new IllegalArgumentException("orderNo为空");
		}
		String[] parts = orderNo.split("O");
		if(parts.length != 2) {
			throw new IllegalArgumentException("orderNo格式错误");
		}
		
		return Integer.parseInt(parts[1]);
	}	
	
	public BizOutwardRequest clone() {
		BizOutwardRequest outwardRequestNew = new BizOutwardRequest();
		outwardRequestNew.setOrderNo(getOrderNo());
		outwardRequestNew.setHandicap(getHandicap());
		outwardRequestNew.setMember(getMember());
		outwardRequestNew.setMemberCode(getMemberCode());
		outwardRequestNew.setAmount(getAmount());
		outwardRequestNew.setCreateTime(getCreateTime());
		outwardRequestNew.setUpdateTime(new Date());
		outwardRequestNew.setStatus(getStatus());
		outwardRequestNew.setRemark(getRemark());
		outwardRequestNew.setReview(getReview());
		outwardRequestNew.setReviewer(getReviewer());
		outwardRequestNew.setTimeConsuming(getTimeConsuming());
		outwardRequestNew.setToAccountName(getToAccountName());
		outwardRequestNew.setToAccount(getToAccount());
		outwardRequestNew.setToAccountOwner(getToAccountOwner());
		outwardRequestNew.setToAccountBank(getToAccountBank());
		outwardRequestNew.setLevel(getLevel());
		return outwardRequestNew;
	}


	/**
	 * 出款类型(出款通道类型)
	 */
	@Transient
	public OutwardRequestType getOutwardRequestType() {
	  return 	OutwardRequestType.getByNumber(this.type);
	}
}
