package com.xinbo.fundstransfer.domain.entity;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.*;

/**
 * BizAccount generated by hbm2java
 */
@Entity
@Table(name = "biz_outward_log")
public class BizOutwardLog implements java.io.Serializable {
	private Long id;

	private int fromId;

	private String toAccount;

	private Date updateTime;

	public BizOutwardLog() {
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "from_id")
	public Integer getFromId() {
		return fromId;
	}

	public void setFromId(Integer fromId) {
		this.fromId = fromId;
	}

	@Column(name = "to_account")
	public String getToAccount() {
		return toAccount;
	}

	public void setToAccount(String toAccount) {
		this.toAccount = toAccount;
	}

	@Column(name = "update_time")
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}
