package com.xinbo.fundstransfer.domain.entity;

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * BizAccountLevel generated by hbm2java
 */
public class BizThirdOut implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int id;
	private int fromid;
	private String fromAccount;
	private String toAccount;
	private String toAccountOwner;
	private String toAccountBank;
	private BigDecimal amount;
	private BigDecimal fee;
	private String remark;
	private String handicap;
	private String orderNo;
	private String member;
	private String level;
	private String createTime;
	private String operator;

	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}

	/**
	 * @param id
	 *            the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the fromid
	 */
	public int getFromid() {
		return fromid;
	}

	/**
	 * @param fromid
	 *            the fromid to set
	 */
	public void setFromid(int fromid) {
		this.fromid = fromid;
	}

	/**
	 * @return the fromAccount
	 */
	public String getFromAccount() {
		return fromAccount;
	}

	/**
	 * @param fromAccount
	 *            the fromAccount to set
	 */
	public void setFromAccount(String fromAccount) {
		this.fromAccount = fromAccount;
	}

	/**
	 * @return the toAccount
	 */
	public String getToAccount() {
		return toAccount;
	}

	/**
	 * @param toAccount
	 *            the toAccount to set
	 */
	public void setToAccount(String toAccount) {
		this.toAccount = toAccount;
	}

	/**
	 * @return the toAccountOwner
	 */
	public String getToAccountOwner() {
		return toAccountOwner;
	}

	/**
	 * @param toAccountOwner
	 *            the toAccountOwner to set
	 */
	public void setToAccountOwner(String toAccountOwner) {
		this.toAccountOwner = toAccountOwner;
	}

	/**
	 * @return the toAccountBank
	 */
	public String getToAccountBank() {
		return toAccountBank;
	}

	/**
	 * @param toAccountBank
	 *            the toAccountBank to set
	 */
	public void setToAccountBank(String toAccountBank) {
		this.toAccountBank = toAccountBank;
	}

	/**
	 * @return the amount
	 */
	public BigDecimal getAmount() {
		return amount;
	}

	/**
	 * @param amount
	 *            the amount to set
	 */
	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	/**
	 * @return the fee
	 */
	public BigDecimal getFee() {
		return fee;
	}

	/**
	 * @param fee
	 *            the fee to set
	 */
	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	/**
	 * @return the remark
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * @param remark
	 *            the remark to set
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * @return the handicap
	 */
	public String getHandicap() {
		return handicap;
	}

	/**
	 * @param handicap
	 *            the handicap to set
	 */
	public void setHandicap(String handicap) {
		this.handicap = handicap;
	}

	/**
	 * @return the orderNo
	 */
	public String getOrderNo() {
		return orderNo;
	}

	/**
	 * @param orderNo
	 *            the orderNo to set
	 */
	public void setOrderNo(String orderNo) {
		this.orderNo = orderNo;
	}

	/**
	 * @return the member
	 */
	public String getMember() {
		return member;
	}

	/**
	 * @param member
	 *            the member to set
	 */
	public void setMember(String member) {
		this.member = member;
	}

	/**
	 * @return the level
	 */
	public String getLevel() {
		return level;
	}

	/**
	 * @param level
	 *            the level to set
	 */
	public void setLevel(String level) {
		this.level = level;
	}

	/**
	 * @return the createTime
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * @param createTime
	 *            the createTime to set
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * @return the operator
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * @param operator
	 *            the operator to set
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	public BizThirdOut(int id, int fromid, String fromAccount, String toAccount, String toAccountOwner,
			String toAccountBank, BigDecimal amount, BigDecimal fee, String remark, String handicap, String orderNo,
			String member, String level, String createTime, String operator) {
		super();
		this.id = id;
		this.fromid = fromid;
		this.fromAccount = fromAccount;
		this.toAccount = toAccount;
		this.toAccountOwner = toAccountOwner;
		this.toAccountBank = toAccountBank;
		this.amount = amount;
		this.fee = fee;
		this.remark = remark;
		this.handicap = handicap;
		this.orderNo = orderNo;
		this.member = member;
		this.level = level;
		this.createTime = createTime;
		this.operator = operator;
	}

	public BizThirdOut() {
		super();
	}

}
