package com.xinbo.fundstransfer.domain.entity;
// Generated 2017-6-27 10:11:57 by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.Map;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * BizTransactionLog generated by hbm2java
 */
@Entity
@Table(name = "biz_transaction_log")
public class BizTransactionLog implements java.io.Serializable {

	private Long id;
	private Date createTime;
	private Integer fromAccount = 0;
	private Integer toAccount;
	private BigDecimal amount;
	private BigDecimal fee;
	private Integer operator;
	private Integer confirmor;
	private Integer type;
	private Long orderId;
	private Long toBanklogId;
	private Long fromBanklogId;
	private String remark;
	private BigDecimal difference;

	private String confirmorUid;
	private String fromAccountNO;
	private String createTimeStr;
	private String typeName;
	private BizIncomeRequest incomeVO;
	private BizBankLog toBankVO;
	private BizBankLog fromBankVo;
	private Map<String, Object> outwardTaskInfo;
	private String fromAlias;
	private String fromOwner;
	private String fromBankType;

	public BizTransactionLog() {
	}

	public BizTransactionLog(Date createTime, Integer fromAccount, int toAccount, BigDecimal amount, BigDecimal fee,
			Integer operator, Integer confirmor, Integer type, Long orderId, Long toBanklogId, Long fromBanklogId) {
		this.createTime = createTime;
		this.fromAccount = fromAccount;
		this.toAccount = toAccount;
		this.amount = amount;
		this.fee = fee;
		this.operator = operator;
		this.confirmor = confirmor;
		this.type = type;
		this.orderId = orderId;
		this.toBanklogId = toBanklogId;
		this.fromBanklogId = fromBanklogId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "from_account")
	public Integer getFromAccount() {
		return this.fromAccount;
	}

	public void setFromAccount(Integer fromAccount) {
		this.fromAccount = fromAccount;
	}

	@Column(name = "to_account")
	public Integer getToAccount() {
		return this.toAccount;
	}

	public void setToAccount(Integer toAccount) {
		this.toAccount = toAccount;
	}

	@Column(name = "amount", precision = 10)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "fee", precision = 10)
	public BigDecimal getFee() {
		return this.fee;
	}

	public void setFee(BigDecimal fee) {
		this.fee = fee;
	}

	@Column(name = "operator")
	public Integer getOperator() {
		return this.operator;
	}

	public void setOperator(Integer operator) {
		this.operator = operator;
	}

	@Column(name = "confirmor")
	public Integer getConfirmor() {
		return this.confirmor;
	}

	public void setConfirmor(Integer confirmor) {
		this.confirmor = confirmor;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "order_id")
	public Long getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	@Column(name = "remark")
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "difference")
	public BigDecimal getDifference() {
		return difference;
	}

	public void setDifference(BigDecimal difference) {
		this.difference = difference;
	}

	@Column(name = "to_banklog_id")
	public Long getToBanklogId() {
		return toBanklogId;
	}

	public void setToBanklogId(Long toBanklogId) {
		this.toBanklogId = toBanklogId;
	}

	@Column(name = "from_banklog_id")
	public Long getFromBanklogId() {
		return fromBanklogId;
	}

	public void setFromBanklogId(Long fromBanklogId) {
		this.fromBanklogId = fromBanklogId;
	}

	@Transient
	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Transient
	public BizIncomeRequest getIncomeVO() {
		return incomeVO;
	}

	public void setIncomeVO(BizIncomeRequest incomeVO) {
		this.incomeVO = incomeVO;
	}

	@Transient
	public BizBankLog getToBankVO() {
		return toBankVO;
	}

	public void setToBankVO(BizBankLog toBankVO) {
		this.toBankVO = toBankVO;
	}

	@Transient
	public BizBankLog getFromBankVo() {
		return fromBankVo;
	}

	public void setFromBankVo(BizBankLog fromBankVo) {
		this.fromBankVo = fromBankVo;
	}

	@Transient
	public String getFromAccountNO() {
		return fromAccountNO;
	}

	public void setFromAccountNO(String fromAccountNO) {
		this.fromAccountNO = fromAccountNO;
	}

	@Transient
	public String getCreateTimeStr() {
		return createTimeStr;
	}

	public void setCreateTimeStr(String createTimeStr) {
		this.createTimeStr = createTimeStr;
	}

	@Transient
	public String getConfirmorUid() {
		return confirmorUid;
	}

	public void setConfirmorUid(String confirmorUid) {
		this.confirmorUid = confirmorUid;
	}

	@Transient
	public Map<String, Object> getOutwardTaskInfo() {
		return outwardTaskInfo;
	}

	public void setOutwardTaskInfo(Map<String, Object> outwardTaskInfo) {
		this.outwardTaskInfo = outwardTaskInfo;
	}

	@Transient
	public String getFromAlias() {
		return fromAlias;
	}

	public void setFromAlias(String fromAlias) {
		this.fromAlias = fromAlias;
	}

	@Transient
	public String getFromOwner() {
		return fromOwner;
	}

	public void setFromOwner(String fromOwner) {
		this.fromOwner = fromOwner;
	}

	@Transient
	public String getFromBankType() {
		return fromBankType;
	}

	public void setFromBankType(String fromBankType) {
		this.fromBankType = fromBankType;
	}
}
