package com.xinbo.fundstransfer.domain.entity;
// Generated 2017-6-27 10:11:57 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysMenuPermission generated by hbm2java
 */
@Entity
@Table(name = "sys_menu_permission", uniqueConstraints = @UniqueConstraint(columnNames = "permission_key"))
public class SysMenuPermission implements java.io.Serializable {

	private Integer id;
	private String permissionKey;
	private String name;
	private String uri;
	private Integer parentId;
	private String icon;
	private Integer priority;//菜单排序

	public SysMenuPermission() {
	}

	public SysMenuPermission(String permissionKey) {
		this.permissionKey = permissionKey;
	}

	public SysMenuPermission(String permissionKey, String name, String uri, Integer parentId, String icon) {
		this.permissionKey = permissionKey;
		this.name = name;
		this.uri = uri;
		this.parentId = parentId;
		this.icon = icon;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "permission_key", unique = true, nullable = false, length = 45)
	public String getPermissionKey() {
		return this.permissionKey;
	}

	public void setPermissionKey(String permissionKey) {
		this.permissionKey = permissionKey;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "uri", length = 60)
	public String getUri() {
		return this.uri;
	}

	public void setUri(String uri) {
		this.uri = uri;
	}

	@Column(name = "parent_id")
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "icon", length = 45)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	@Column(name = "priority")
	public Integer getPriority() {
		return priority;
	}

	public void setPriority(Integer priority) {
		this.priority = priority;
	}
}
