package com.xinbo.fundstransfer.domain.entity;
// Generated 2017-6-27 10:11:57 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysRoleMenuPermission generated by hbm2java
 */
@Entity
@Table(name = "sys_role_menu_permission")
public class SysRoleMenuPermission implements java.io.Serializable {

	private Integer id;
	private Integer roleId;
	private Integer menuPermissionId;

	public SysRoleMenuPermission() {
	}

	public SysRoleMenuPermission(int roleId, int menuPermissionId) {
		this.roleId = roleId;
		this.menuPermissionId = menuPermissionId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "role_id", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "menu_permission_id", nullable = false)
	public Integer getMenuPermissionId() {
		return this.menuPermissionId;
	}

	public void setMenuPermissionId(Integer menuPermissionId) {
		this.menuPermissionId = menuPermissionId;
	}

}
