package com.xinbo.fundstransfer.domain.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SysUserProfile generated by hbm2java
 */
@Entity
@Table(name = "sys_user_profile", uniqueConstraints = @UniqueConstraint(columnNames = {"property_key", "user_id"}))
public class SysUserProfile implements java.io.Serializable {

    private Integer id;
    private Integer userId;
    private String propertyKey;
    private String propertyValue;
    private String propertyName;
    private String isEnable;

    public SysUserProfile() {

    }

    public SysUserProfile(int userId) {
        this.userId = userId;
    }

    public SysUserProfile(int userId, String propertyKey, String propertyValue) {
        this.userId = userId;
        this.propertyKey = propertyKey;
        this.propertyValue = propertyValue;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "user_id", nullable = false)
    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Column(name = "property_key", length = 45)
    public String getPropertyKey() {
        return this.propertyKey;
    }

    public void setPropertyKey(String propertyKey) {
        this.propertyKey = propertyKey;
    }

    @Column(name = "property_value", length = 200)
    public String getPropertyValue() {
        return this.propertyValue;
    }

    public void setPropertyValue(String propertyValue) {
        this.propertyValue = propertyValue;
    }

    @Column(name = "property_name", length = 200)
    public String getPropertyName() {
        return propertyName;
    }

    public void setPropertyName(String propertyName) {
        this.propertyName = propertyName;
    }

    @Column(name = "is_enable", length = 1)
    public String getIsEnable() {
        return isEnable;
    }

    public void setIsEnable(String isEnable) {
        this.isEnable = isEnable;
    }

    /*
     * @ManyToOne(cascade=CascadeType.ALL,optional=false)
	 * 
	 * @JoinColumn(name = "user_id",insertable = false,updatable = false) public
	 * SysUser getSysUser() { return sysUser; }
	 * 
	 * public void setSysUser(SysUser sysUser) { this.sysUser = sysUser; }
	 */
}
