package com.xinbo.fundstransfer.domain.entity;
// Generated 2017-6-27 10:11:57 by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SysUserDataPermission generated by hbm2java
 */
@Entity
@Table(name = "sys_user_data_permission")
public class SysUserDataPermission implements java.io.Serializable {

	private Long id;
	private int dataPermissionId;
	private int userId;

	public SysUserDataPermission() {
	}

	public SysUserDataPermission(int dataPermissionId, int userId) {
		this.dataPermissionId = dataPermissionId;
		this.userId = userId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "data_permission_id", nullable = false)
	public int getDataPermissionId() {
		return this.dataPermissionId;
	}

	public void setDataPermissionId(int dataPermissionId) {
		this.dataPermissionId = dataPermissionId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
