---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/3/19 15:56
---描述:新公司入款 1.5.8接口 选择最近最少使用的卡返回给平台支付
---
local key = KEYS[1];--通道idkey 'pocId:accountIds:hash:123'
local accountIdsStr = ARGV[1];--待选定的账号id "1,2,3,4"
local time = ARGV[2];--当前时间
local exist = redis.call('exists', key);--是否存在key
local accountId2Use = 0;--初始化选定的卡号id
local lruAccountIdCount = 0;--初始化最近最少使用的次数
if accountIdsStr == '' or accountIdsStr == nil then
    return accountId2Use;
end
local accountIds = {};
string.gsub(accountIdsStr, "[^" .. '|' .. "]+", function(w)
    table.insert(accountIds, w)
end);
if accountIds == nil or #accountIds == 0 then
    return accountId2Use;
end
if exist ~= nil and exist > 0 then
    local useOld = true;--初始化使用旧卡
    local usedAccountIdCount = nil;
    for i, v in pairs(accountIds) do
        usedAccountIdCount = redis.call('hget', key, v);
        if not usedAccountIdCount or usedAccountIdCount == nil or usedAccountIdCount == '' then
            useOld = false;
            accountId2Use = v;
            redis.call('HSET', key, accountId2Use, time);--不存在则新增使用记录
            break ;
        else
            --如果只有一张卡
            if #accountIds == 1 then
                accountId2Use = v;
                break ;
            elseif i == 1 then
                lruAccountIdCount = tonumber(usedAccountIdCount);--初始化最近最少使用的值
                accountId2Use = v;
            end
            if tonumber(usedAccountIdCount) <= lruAccountIdCount then
                lruAccountIdCount = tonumber(usedAccountIdCount);
                accountId2Use = v;
            end
        end
    end
    if useOld and tonumber(accountId2Use) ~= 0 then
        redis.call('HSET', key, accountId2Use, time);--新增使用记录
    end
else
    redis.call('HSET', key, accountIds[1], time);
    accountId2Use = accountIds[1];
end
return accountId2Use;