---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/7/12 16:06
---
--- 下发任务 锁定 draw:task:user:lock:card
---
--- 第三方入款 下发 出款卡锁 key:  outcard:need:third:draw:user:locked:5:123  zset
--- 下发卡 锁 thirdInAccount:withdraw:lockTargetAccId:byUser:5:261612  set
---
local key = KEYS[1];
local accountIds = ARGV[2];
local userId = ARGV[1];
local useOldDrawManner = ARGV[3];---标识是否使用旧的第三方下发
local lockedTime = ARGV[4];
local keyToSave = key .. ':' .. userId;
local ret = 0;
local accountId = {};
if  userId == nil or accountId == nil then
    return ret;
else
    string.gsub(accountIds, '[^' .. ',' .. ']+', function(w)
        table.insert(accountId, w)
    end)
    if useOldDrawManner ~= nil and 1 == tonumber(useOldDrawManner) then
        local locked = {};
        ---第三方入款 下发卡 锁key set
        local key1 = 'thirdInAccount:withdraw:lockTargetAccId:byUser:*:*';
        ---第三方入款 出款卡 锁key zset
        local key2 = 'outcard:need:third:draw:user:locked:*:*';
        --- 获取 key的集合
        local key1s = redis.call("keys", key1);
        if key1s ~= nil then
            local key1sLen = #key1s;
            if key1sLen > 0 then
                for i = 1, key1sLen do
                    local key11 = key1s[i];
                    local val11 = redis.call("smembers", key11);
                    if val11 ~= nil and #val11 > 0 then
                        for j = 1, #val11 do
                            table.insert(locked, val11[j]);
                        end
                    end
                end
            end

        end
        local key2s = redis.call("keys", key2);
        if key2s ~= nil then
            local key2sLen = #key2s;
            if key2sLen > 0 then
                for i = 1, key2sLen do
                    local key22 = key2s[i];
                    local val22 = redis.call("zrange", key22, 0, -1);
                    if val22 ~= nil and #val22 > 0 then
                        for j = 1, #val22 do
                            table.insert(locked, val22[j]);
                        end
                    end
                end
            end
        end

        local accountIdLen = #accountId;
        local lockedLen = #locked;
        local outter = {};
        local inner = {};
        if accountIdLen < lockedLen then
            outter = accountId;
            inner = locked;
        else
            outter = locked;
            inner = accountId;
        end
        local existed = false;
        for i = 1, #outter do
            for j = 1, #inner do
                if outter[i] == inner[j] then
                    existed = true;
                    break ;
                end
            end
            if existed then
                break ;
            end
        end
        if not existed then
            local key3 = key .. ':*';
            local key3s = redis.call("keys", key3);
            if  key3s == nil or #key3s == 0 then
                local accountIdLen = #accountId;
                for i = 1, accountIdLen do
                    local res = redis.call("ZADD", keyToSave, lockedTime, accountId[i]);
                    ret = ret + res;
                end
            else
                local existed2 = {};
                for i = 1, #key3s do
                    local key33 = key3s[i];
                    local val33 = redis.call("ZRANGE", key33, 0, -1);
                    if val33 ~= nil then
                        for j = 1, #val33 do
                            table.insert(existed2, val33[j]);
                        end
                    end
                end
                local existed2Len = #existed2;
                local accountIdLen2 = #accountId;
                local outter2 = {};
                local inner2 = {};
                if accountIdLen2 > existed2Len then
                    inner2 = accountId;
                    outter2 = existed2;
                else
                    inner2 = existed2;
                    outter2 = accountId;
                end
                local existed3 = false;
                for i = 1, #outter2 do
                    for j = 1, #inner2 do
                        if outter2[i] == inner2[j] then
                            existed3 = true;
                        end
                    end
                end
                if not existed3 then
                    local accountIdLen4 = #accountId;
                    for i = 1, accountIdLen4 do
                        local res = redis.call("ZADD", keyToSave, lockedTime, accountId[i]);
                        ret = ret + res;
                    end
                end
            end
        end
    else
        local key3 = key .. ':*';
        local key3s = redis.call("keys", key3);
        if   key3s == nil or #key3s == 0 then
            local accountIdLen = #accountId;
            for i = 1, accountIdLen do
                local res = redis.call("ZADD", keyToSave, lockedTime, accountId[i]);
                ret = ret + res;
            end
        else
            local existed2 = {};
            for i = 1, #key3s do
                local key33 = key3s[i];
                local val33 = redis.call("ZRANGE", key33, 0, -1);
                if val33 ~= nil then
                    for j = 1, #val33 do
                        table.insert(existed2, val33[j]);
                    end
                end
            end
            local existed2Len = #existed2;
            local accountIdLen2 = #accountId;
            local outter2 = {};
            local inner2 = {};
            if accountIdLen2 > existed2Len then
                inner2 = accountId;
                outter2 = existed2;
            else
                inner2 = existed2;
                outter2 = accountId;
            end
            local existed3 = false;
            for i = 1, #outter2 do
                for j = 1, #inner2 do
                    if outter2[i] == inner2[j] then
                        existed3 = true;
                    end
                end
            end
            if not existed3 then
                local accountIdLen4 = #accountId;
                for i = 1, accountIdLen4 do
                    local ret = redis.call("ZADD", keyToSave, lockedTime, accountId[i]);
                    ret = ret + res;
                end
            end
        end
    end
end
return ret;




